# SwiftLint Configuration for FluidSimApp

# Disabled rules
disabled_rules:
  - trailing_whitespace
  - line_length

# Opt-in rules
opt_in_rules:
  - empty_count
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - discouraged_object_literal
  - empty_string
  - explicit_init
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - strict_fileprivate
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

# Included paths
included:
  - App
  - Core
  - UI
  - Extensions
  - Tests

# Excluded paths
excluded:
  - Pods
  - Scripts
  - Config
  - Resources
  - Supporting

# Custom rule configurations
line_length:
  warning: 120
  error: 200

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1200

function_body_length:
  warning: 50
  error: 100

identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 40
    error: 50
  excluded:
    - i
    - j
    - x
    - y
    - dx
    - dy
    - dt
    - id
    - uv
    - r
    - g
    - b
    - a

custom_rules:
  arabic_comments:
    name: "Arabic Comments Support"
    regex: '\/\/.*[\u0600-\u06FF]'
    match_kinds:
      - comment
    message: "Arabic comments are allowed and encouraged"
    severity: none